# Generated by Django 5.1.3 on 2025-04-13 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width_mm', models.FloatField()),
                ('height_mm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_paper_width', models.FloatField(blank=True, null=True)),
                ('custom_paper_height', models.FloatField(blank=True, null=True)),
                ('sticker_width', models.FloatField()),
                ('sticker_height', models.FloatField()),
                ('top_margin', models.FloatField()),
                ('bottom_margin', models.FloatField()),
                ('left_margin', models.FloatField()),
                ('right_margin', models.FloatField()),
                ('horizontal_spacing', models.FloatField()),
                ('vertical_spacing', models.FloatField()),
                ('stickers_per_row', models.IntegerField()),
                ('num_rows', models.IntegerField()),
                ('total_stickers', models.IntegerField()),
                ('layout_svg', models.TextField()),
                ('paper_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.papersize')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
