# Generated by Django 5.1.3 on 2025-04-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Layout', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_width', models.FloatField(blank=True, null=True)),
                ('custom_height', models.FloatField(blank=True, null=True)),
                ('margin_top', models.FloatField(default=10)),
                ('margin_right', models.FloatField(default=10)),
                ('margin_bottom', models.FloatField(default=10)),
                ('margin_left', models.FloatField(default=10)),
                ('sticker_width', models.FloatField()),
                ('sticker_height', models.FloatField()),
                ('horizontal_spacing', models.FloatField(default=2)),
                ('vertical_spacing', models.FloatField(default=2)),
                ('original_image', models.ImageField(upload_to='stickers/')),
                ('layout_data', models.JSONField(blank=True, null=True)),
                ('paper_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.papersize')),
            ],
        ),
        migrations.DeleteModel(
            name='SavedLayout',
        ),
    ]
