# Generated by Django 5.1.3 on 2025-04-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stickerlayout_delete_savedlayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerlayout',
            name='custom_height',
        ),
        migrations.RemoveField(
            model_name='stickerlayout',
            name='custom_width',
        ),
    ]
